### ISSUE TITLE
Use process problem

### ISSUE THREAD

**Issue by popular1119** [LarsG21/EIT_reconstruction#1]
Hello, I feel great after reading the article you wrote, but I have a suggestion: you upload too much material, which makes people feel too confusing. It would be great if there is a usage process.
Thanks!

**Comment by LarsG21** [comment]
Hey, I think this is a misunderstanding. I didn't wrote the Article to "pyeit". I am just using parts of it for my own project.  The original repo can be found here: https://github.com/eitcom/pyEIT. Yes, I know the repo is kind of messy at the moment, but it is still "work in progress" and in an early stage XD I will clean it up at the end. Thank you for your feedback.
